-- VHDL Entity git_UART_GUI.BD1.symbol
--
-- Created:
--          by - waly.UNKNOWN (EGC-WALY-LT)
--          at - 00:18:47 05/11/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 2 Mar 2020 at 18:07:13
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;

ENTITY BD1 IS
   PORT( 
      clk  : IN     std_logic;
      d    : IN     std_logic;
      load : IN     std_logic;
      rst  : IN     std_logic;
      set  : IN     std_logic;
      q    : OUT    std_logic;
      qb   : OUT    std_logic
   );

-- Declarations

END BD1 ;

--
-- VHDL Architecture git_UART_GUI.BD1.struct
--
-- Created:
--          by - waly.UNKNOWN (EGC-WALY-LT)
--          at - 00:18:47 05/11/2020
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2020.2 Built on 2 Mar 2020 at 18:07:13
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_arith.all;


ARCHITECTURE struct OF BD1 IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.12) for instance 'U_0' of 'adff'
   SIGNAL mw_U_0reg_cval : std_logic;


BEGIN

   -- ModuleWare code(v1.12) for instance 'U_0' of 'adff'
   q <= mw_U_0reg_cval;
   qb <= NOT(mw_U_0reg_cval);
   u_0seq_proc: PROCESS (clk, rst, set)
   BEGIN
      IF (rst = '1') THEN
         mw_U_0reg_cval <= '0';
      ELSIF (set = '1') THEN
         mw_U_0reg_cval <= '1';
      ELSIF (clk'EVENT AND clk='1') THEN
         IF (load = '1') THEN
            mw_U_0reg_cval <= d;
         END IF;
      END IF;
   END PROCESS u_0seq_proc;

   -- Instance port mappings.

END struct;
